name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.28.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.3.0
  test: ^0.12.30
