name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+1

dev_dependencies:
  angular_test: ^1.0.2-alpha+1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.21

dependency_overrides:
  analyzer: ^0.31.0-alpha.1

transformers:
- angular:
    entry_points:
    - web/main.dart
    - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
